### ISSUE TITLE
Works like a charm! 

### ISSUE THREAD

**Issue by web-programmer-here** [eregnier/vue3-gmap-custom-marker#1]
This is amazing! thank you so much for this! I just tested it out and it works like a charm! 
I am facing one minor issue that older markers exist even after I clear them

I have all my locations in an array of object `locations`

```js
const locations = ref([]);
....
<gmap-custom-marker
    v-for="(location, index) in locations"
    :key="index"
    :marker="{ lat: location.lat, lng: location.lng }"
>
   <img ... />
</gmap-custom-marker>
```

I update that array with button clicks to load new locations, but now old places exist on the map. 
Also console log I keep getting `TypeError: this.$overlay is undefined`, I will run more tests and maybe create a sandbox for testing. 

Again thank you for this amazing work! 🥇

**Comment by web-programmer-here** [comment]
@eregnier here is the sandbox showing how the location marker is updated without using custom marker

https://codesandbox.io/s/friendly-haslett-e2xc79?file=/src/frontend/components/Content.vue

and here is one using custom marker that gives `this.$overlay is undefined` error

https://codesandbox.io/s/vigilant-turing-1e4te4?file=/src/frontend/components/Content.vue

**Comment by web-programmer-here** [comment]
@eregnier did you have a chance to look at the sandboxes? I was not able to fix this issue

**Comment by eregnier** [comment]
I had no more time until now. I'll try to find time soon to fix this.

**Comment by eregnier** [comment]
hey @web-programmer-here , I made a change in the component. It should fix your issue. Can you try and let me know if this is ok for you now ?

**Comment by web-programmer-here** [comment]
@eregnier thanks for the quick fix, I tested it again but sometimes it doesnt update the markers
so here is the sandbox

https://codesandbox.io/s/vigilant-turing-1e4te4?file=/src/frontend/components/Content.vue

<img width="605" alt="image" src="https://user-images.githubusercontent.com/81479051/156266641-f0678b0a-8973-4138-af82-29f03c20fd58.png">

only two locations should be listed but the map shows 4
```
Info: 40.70245807872047 | -74.05451818337261
Info: 40.672198572646835 | -74.07562922927289
```
